version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - echo running build commands in $stg
      - npm install -g serverless
      - sls deploy --stage $stg
      - echo all build commands successfully ran